#
# Edit this file to control the behaviour of the parser
#

# Proxy to use for all internet connections in the parser
# Leave commented out to disable the use of the proxy
#
# Using a web caching proxy is especially useful during development
# to speed up the running of the parser.
#
# We've been using a "free" for private use caching proxy called
# WebAssistant (http://www.proxy-offline-browser.com/)
# It should also be possible to use Squid (http://www.squid-cache.org/) but so
# far the configuration for caching dynamic content in Squid has eluded us.

proxy:
    host: localhost
    port: 8080

# The root directory of the patched Australian version of the TheyWorkForYou
# website.
# For example, Under Mac OS X this is likely to be something like:
web_root: "/Library/WebServer/Documents/openaustralia"
# Under Linux, this is likely to be something like:
#web_root: "/var/www/openaustralia-app"

# Should hopefully not have to change anything below here

# Links to the biographies of all *current* house members and senators
current_house_members_url: "http://parlinfoweb.aph.gov.au/piweb/browse.aspx?path=Parliamentary%20Handbook%20%3E%20Biographies%20%3E%20Current%20Members"
current_senate_members_url: "http://parlinfoweb.aph.gov.au/piweb/browse.aspx?path=Parliamentary%20Handbook%20%3E%20Biographies%20%3E%20Current%20Senators"
# Links to the biographies of all *former* senators and representatives
former_members_house_and_senate_url: "http://parlinfoweb.aph.gov.au/piweb/browse.aspx?path=Parliamentary%20Handbook%20%3E%20Biographies%20%3E%20Former%20Senators%20and%20Members"
